apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-flask
  template:
    metadata:
      labels:
        app: keda-flask
    spec:
      containers:
      - name: keda-flask
        image: suhailaplha/keda-webapp:v1
        ports:
        - containerPort: 80
